// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tikwwaarerubrdwzthpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpa3d3YWFyZXJ1YnJkd3p0aHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTQ1OTAsImV4cCI6MjA2MDYzMDU5MH0.xKxtiO2RgEEgIYbvIY665mkLLFEMdXPxkpsEF3McPvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);